### ISSUE TITLE
Move reporting module to webserver

### ISSUE THREAD

**Issue by cmspinto** [ices-taf/SmartDotsReport_template#1]
### Tasks

- [x] constrain to isApproved == true in view
- [x] Get advanced, Basic from view
- [x] Warn about / remove dots close to centre in view
- [ ] get GUID from view
- [ ] get event title from view

**Comment by colinpmillar** [comment]
keep isApproved filter in code for now e5489c8c90b292af457c8a0a450de9a9eb10541b
